goal:
	g++ -g -Dlinux -I../../../include/ -I -Wall -ansi -pedantic-errors -I../../../examples/matprod -I../../../examples/matprod/sym -c my.cpp;
	g++ -g -Dlinux -I../../../include/ -I -Wall -ansi -pedantic-errors -I../../../examples/matprod -I../../../examples/matprod/sym -o my my.o -larpack -lblas -llapack -lgfortran;
