
language: cpp

compiler: gcc

cache:
  - apt
  - ccache

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - gfortran
      - libopenblas-dev
      - liblapack-dev
      - libarpack2-dev
      - libmetis-dev
      - libsuitesparse-dev
    update: true
  homebrew:
    packages:
      - arpack
      - superlu
      - suite-sparse
    update: true

env:
  - SUPERLU=ON BLAS=SYSTEM CHOLMOD=ON UMFPACK=ON

before_script:
  # linux needs SuperLU from source (APT on xenial libsuperlu-dev is still 4.3)
  - if [ "$TRAVIS_OS_NAME" = "linux" -a "$SUPERLU" = "ON" ]; then ./install-superlu.sh ; fi
#  - if [ "$CHOLMOD" = "ON" -o "$UMFPACK" = "ON" ]; then ./install-suitesparse.sh ; fi
#  - if [[ ( "$TRAVIS_OS_NAME" = "linux" ) && ( "$CHOLMOD" = "ON" || "$UMFPACK" = "ON" ) ]]; then ./install-suitesparse.sh ; fi
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=$PWD/install -DSUPERLU=$SUPERLU -DUMFPACK=$UMFPACK -DCHOLMOD=$CHOLMOD ..

script:
  - make install
  - make examples -j2
